services:
  frontend:
    build:
      context: ./frontend
      target: ${TARGET:-development}
    volumes:
      - ./frontend:/app
      - ./certs:/app/certs:ro  # Mount certificates
      - pnpm-store:/root/.local/share/pnpm/store
      - pnpm-modules:/app/node_modules
    environment:
      - VITE_API_URL=${API_URL:-https://localhost:8443}
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      target: ${TARGET:-development}
    volumes:
      - ./backend:/app
      - ./certs:/app/certs:ro  # Mount certificates
    environment:
      - CORS_ORIGINS=${CORS_ORIGINS:-https://localhost:8443}
    ports:
      - "8000:8000"

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro
    ports:
      - "8443:443"
    depends_on:
      - frontend
      - backend

volumes:
  pnpm-store:
  pnpm-modules: