services:

  backend:
    build:
      context: ./
      dockerfile: backend/Dockerfile
    container_name: duncan-backend
    ports:
      - "3174:8000"
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - app-network
  
  frontend:
    build:
      context: ./
      dockerfile: frontend/Dockerfile
    container_name: duncan-frontend
    ports:
      - "3173:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge